// Framework - Servidor
import type { Metadata } from "next";

// Css
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';

// Provider
import NextAuthSessionProvider from "@/providers/sessionProvider";

// Biblioteca
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="pt-br">
      <body >
        <NextAuthSessionProvider>
          {children}
          <ToastContainer autoClose={3000} />
        </NextAuthSessionProvider>
      </body>
    </html>
  );
}
