// Css
import "../../css/globals.css";

// React 
import { ReactNode } from "react";

// Framework / Servidor
import { getServerSession } from "next-auth";
import { nextAuthOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";

// Tipagem
interface PublicLayoutProps {
  children: ReactNode
}

export const metadata = {
  title: 'Login',
  description: 'Generated by Next.js',
}

export default async function PublicLayout({ children }: PublicLayoutProps) {
  const session = await getServerSession(nextAuthOptions)

  if (session) {
    redirect('/')
  }

  return (
    <div>
      {children}
    </div>
  )
}
